language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t reacttesting -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true reacttesting npm run test

after_success:
  - docker build -t omarzaamtest/multi-docker-client-test ./client
  - docker build -t omarzaamtest/multi-docker-nginx ./nginx
  - docker build -t omarzaamtest/multi-docker-server ./server
  - docker build -t omarzaamtest/multi-docker-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push omarzaamtest/multi-docker-nginx
  - docker push omarzaamtest/multi-docker-server
  - docker push omarzaamtest/multi-docker-worker
  - docker push omarzaamtest/multi-docker-client
  
# Log in to docker CLI


deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-742518153702"
  bucket_path: "docker-multi"
  on:
    branch: master


  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
